/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "50a5ca15f0579ee3e6fc5ddec749affcc11b9165"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
